name: Create Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    uses: PlainsightAI/gh-actions-public/.github/workflows/filter-release.yaml@main
    with:
      docker_image: plainsightai/openfilter-vizcal
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
